import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { QRCodeCanvas } from 'qrcode.react';
import Modal from '../components/Modal.jsx';
import { ToastContainer, useToast } from '../hooks/useToast.jsx';
import {
  fetchPersonnel, createPersonnel, updatePersonnel, archivePersonnel, fetchAssignableInventory,
  assignAsset, fetchPersonnelAssets, fetchAssetDetails, addMaintenance, updateMaintenance, removeMaintenance, returnAsset, transferAsset, phaseOutAsset,
} from '../api/personnelAssets.js';

const today = new Date().toISOString().slice(0, 10);
const money = value => `₱${Number(value || 0).toLocaleString('en-PH', { minimumFractionDigits: 2 })}`;
const date = value => value ? new Date(value).toLocaleDateString('en-PH') : '—';
const errorMessage = err => err.response?.data?.message || err.message || 'Something went wrong.';
const emptyPerson = { employee_id:'', full_name:'', position:'', department:'', email:'', contact_number:'', employment_status:'active', notes:'', profile_photo:'' };

export default function Feature() {
  const { toasts, showToast } = useToast();
  const [people,setPeople]=useState([]), [loading,setLoading]=useState(true), [search,setSearch]=useState('');
  const [personForm,setPersonForm]=useState(null), [assignPerson,setAssignPerson]=useState(null), [itemsPerson,setItemsPerson]=useState(null);
  const load=useCallback(async()=>{setLoading(true);try{setPeople(await fetchPersonnel(search));}catch(e){showToast(errorMessage(e),'error');}finally{setLoading(false);}},[search,showToast]);
  useEffect(()=>{const id=setTimeout(load,250);return()=>clearTimeout(id);},[load]);
  async function archive(person){if(!confirm(`Archive ${person.full_name}? Their history will be preserved.`))return;try{const r=await archivePersonnel(person.id);showToast(r.message);load();}catch(e){showToast(errorMessage(e),'error');}}

  const stats=useMemo(()=>({people:people.length,assets:people.reduce((n,p)=>n+Number(p.assigned_item_count),0),departments:new Set(people.map(p=>p.department).filter(Boolean)).size}),[people]);
  return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-slate-100">
    <div className="max-w-screen-xl mx-auto px-6 lg:px-8 py-10">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-8">
        <div><p className="text-sm font-semibold text-blue-600 mb-2">RECORD KEEPING</p><h1 className="text-4xl font-bold text-slate-800">Personnel Assets</h1><p className="mt-2 text-sm text-slate-500">Track accountable equipment, assignments, maintenance, and asset history.</p></div>
        <button onClick={()=>setPersonForm(emptyPerson)} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-700">+ Add Personnel</button>
      </div>
      <div className="grid sm:grid-cols-3 gap-4 mb-8"><Stat label="Active personnel" value={stats.people}/><Stat label="Assigned assets" value={stats.assets}/><Stat label="Departments" value={stats.departments}/></div>
      <div className="mb-6"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, employee ID, or department..." className="w-full md:w-96 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm shadow-sm outline-none focus:border-blue-400" /></div>
      {loading?<div className="py-20 text-center text-slate-400">Loading personnel...</div>:people.length===0?<Empty onAdd={()=>setPersonForm(emptyPerson)}/>:<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-6">{people.map(p=><PersonnelCard key={p.id} person={p} onEdit={()=>setPersonForm(p)} onAssign={()=>setAssignPerson(p)} onItems={()=>setItemsPerson(p)} onArchive={()=>archive(p)}/>)}</div>}
    </div>
    <PersonnelModal person={personForm} onClose={()=>setPersonForm(null)} onSaved={()=>{setPersonForm(null);load();showToast('Personnel record saved.');}} />
    <AssignModal person={assignPerson} onClose={()=>setAssignPerson(null)} onSaved={()=>{setAssignPerson(null);load();showToast('Item assigned successfully.');}} />
    <AssetsModal person={itemsPerson} people={people} onClose={()=>setItemsPerson(null)} onChanged={()=>{load();}} showToast={showToast}/>
    <ToastContainer toasts={toasts}/>
  </main>;
}

function Stat({label,value}){return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-slate-800">{value}</p></div>}
function Empty({onAdd}){return <div className="rounded-3xl border-2 border-dashed border-blue-200 bg-white/70 py-20 text-center"><div className="text-4xl">👥</div><h2 className="mt-4 text-xl font-bold text-slate-800">No personnel records yet</h2><p className="mt-2 text-sm text-slate-500">Add the first person to begin assigning accountable assets.</p><button onClick={onAdd} className="mt-5 text-sm font-semibold text-blue-600">Add Personnel →</button></div>}
function PersonnelCard({person,onEdit,onAssign,onItems,onArchive}){const initials=person.full_name.split(' ').map(v=>v[0]).slice(0,2).join('').toUpperCase();return <article className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm hover:shadow-lg transition-shadow">
  <div className="flex gap-4"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center text-xl font-bold text-white">{person.profile_photo?<img src={person.profile_photo} className="h-full w-full object-cover" alt=""/>:initials}</div><div className="min-w-0"><h2 className="truncate text-lg font-bold text-slate-800">{person.full_name}</h2><p className="truncate text-sm text-slate-500">{person.position||'No position specified'}</p><p className="mt-1 text-xs font-medium text-blue-600">{person.employee_id} · {person.department||'No department'}</p></div></div>
  <div className="my-5 flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span className="text-xs text-slate-500">Assigned items</span><span className="text-lg font-bold text-slate-800">{person.assigned_item_count}</span></div>
  <div className="grid grid-cols-2 gap-2"><Btn onClick={onItems}>View Items</Btn><Btn onClick={onAssign} blue>Assign Item</Btn><Btn onClick={onEdit}>Edit</Btn><Btn onClick={onArchive} danger>Archive</Btn></div>
  </article>}
function Btn({children,onClick,blue,danger}){return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-semibold ${blue?'bg-blue-600 text-white hover:bg-blue-700':danger?'bg-red-50 text-red-600 hover:bg-red-100':'bg-slate-100 text-slate-700 hover:bg-slate-200'}`}>{children}</button>}

function PersonnelModal({person,onClose,onSaved}){const [form,setForm]=useState(person||emptyPerson),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>setForm(person||emptyPerson),[person]);if(!person)return null;
  const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
  async function photo(e){const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024){setError('Profile photo must be 2 MB or smaller.');return;}const reader=new FileReader();reader.onload=()=>setForm(v=>({...v,profile_photo:reader.result}));reader.readAsDataURL(file);}
  async function submit(e){e.preventDefault();setSaving(true);setError('');try{person.id?await updatePersonnel(person.id,form):await createPersonnel(form);onSaved();}catch(err){setError(errorMessage(err));}finally{setSaving(false);}}
  return <Modal open onClose={onClose} title={person.id?'Edit Personnel':'Add Personnel'} subtitle="Store the accountable person's office information."><form onSubmit={submit} className="grid sm:grid-cols-2 gap-4">
    <div className="sm:col-span-2 flex items-center gap-4"><div className="h-20 w-20 overflow-hidden rounded-2xl bg-slate-100 flex items-center justify-center">{form.profile_photo?<img src={form.profile_photo} className="h-full w-full object-cover" alt="Preview"/>:<span className="text-2xl">👤</span>}</div><label className="cursor-pointer rounded-lg border border-slate-200 px-4 py-2 text-sm font-medium">Choose profile photo<input type="file" accept="image/*" className="hidden" onChange={photo}/></label></div>
    <Field label="Employee ID *" name="employee_id" value={form.employee_id} onChange={change} required/><Field label="Full name *" name="full_name" value={form.full_name} onChange={change} required/><Field label="Position" name="position" value={form.position||''} onChange={change}/><Field label="Department / Office" name="department" value={form.department||''} onChange={change}/><Field label="Email" type="email" name="email" value={form.email||''} onChange={change}/><Field label="Contact number" name="contact_number" value={form.contact_number||''} onChange={change}/><Select label="Employment status" name="employment_status" value={form.employment_status} onChange={change} options={['active','inactive','separated']}/><div/>
    <Area label="Notes" name="notes" value={form.notes||''} onChange={change} className="sm:col-span-2"/>{error&&<Error text={error}/>}<Submit saving={saving} text="Save Personnel"/>
  </form></Modal>}

function AssignModal({person,onClose,onSaved}){const initial=useCallback(()=>({inventory_item_id:'',serialized_asset_id:'',personnel_id:person?.id||'',quantity:'1',asset_code:'',item_type:'',unit_price:'',procured_at:'',date_ordered:'',date_procured:'',assigned_at:today,condition:'good',notes:''}),[person]);const [inventory,setInventory]=useState([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[form,setForm]=useState(initial);useEffect(()=>{if(!person)return;setForm(initial());setError('');fetchAssignableInventory().then(setInventory).catch(e=>setError(errorMessage(e)));},[person,initial]);if(!person)return null;
  function choose(e){const key=e.target.value,item=inventory.find(i=>`${i.source_type}:${i.source_id}`===key);setForm(v=>({...v,inventory_item_id:item?.id||'',serialized_asset_id:item?.source_type==='serialized'?item.source_id:'',quantity:'1',item_type:item?.name||'',unit_price:item?.unit_price||'',procured_at:item?.supplier||'',date_ordered:item?.date_ordered?.slice(0,10)||'',date_procured:item?.date_procured?.slice(0,10)||'',asset_code:item?.asset_code||(item?.sku?`${item.sku}-`:''),}));}
  const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));async function submit(e){e.preventDefault();setSaving(true);setError('');try{await assignAsset(form);onSaved();}catch(err){setError(errorMessage(err));}finally{setSaving(false);}}
  return <Modal open onClose={onClose} title={`Assign Item to ${person.full_name}`} subtitle="One inventory unit becomes a uniquely tracked physical asset." maxWidth="max-w-3xl"><form onSubmit={submit} className="grid sm:grid-cols-2 gap-4">
    <label className="sm:col-span-2 text-sm font-medium text-slate-700">Inventory item *<select required value={form.inventory_item_id ? `${form.serialized_asset_id?'serialized':'inventory'}:${form.serialized_asset_id||form.inventory_item_id}` : ''} onChange={choose} className={inputClass}><option value="">Select an available item</option>{inventory.map(i=><option key={`${i.source_type}:${i.source_id}`} value={`${i.source_type}:${i.source_id}`}>{i.name}{i.asset_code?` — returned asset ${i.asset_code}`:` — ${i.quantity} ${i.unit||'pcs'} available`}</option>)}</select></label>
    <Field label="Item type *" name="item_type" value={form.item_type} onChange={change} required/><Field label="Quantity *" type="number" min="1" max={inventory.find(i=>i.id===Number(form.inventory_item_id))?.quantity||100} name="quantity" value={form.quantity} onChange={change} required disabled={!!form.serialized_asset_id}/><Field label={Number(form.quantity)>1?'Item code prefix *':'Unique item code *'} name="asset_code" value={form.asset_code} onChange={change} required readOnly={!!form.serialized_asset_id} placeholder="e.g. PC-ICT-001"/><Field label="Unit price" type="number" step="0.01" name="unit_price" value={form.unit_price} onChange={change}/><Field label="Procured at / Supplier" name="procured_at" value={form.procured_at} onChange={change}/><Field label="Date ordered" type="date" name="date_ordered" value={form.date_ordered} onChange={change}/><Field label="Date procured" type="date" name="date_procured" value={form.date_procured} onChange={change}/><Field label="Date assigned" type="date" name="assigned_at" value={form.assigned_at} onChange={change} required/><Select label="Condition" name="condition" value={form.condition} onChange={change} options={['new','good','fair','poor','damaged']}/>{Number(form.quantity)>1&&<p className="sm:col-span-2 rounded-lg bg-blue-50 p-3 text-xs text-blue-700">Each physical unit will receive its own code: {form.asset_code||'CODE'}-001, -002, and so on.</p>}<Area label="Assignment notes" name="notes" value={form.notes} onChange={change} className="sm:col-span-2"/>{error&&<Error text={error}/>}<Submit saving={saving} text="Assign Item"/>
  </form></Modal>}

function AssetsModal({person,people,onClose,onChanged,showToast}){const [assets,setAssets]=useState([]),[loading,setLoading]=useState(true),[detailId,setDetailId]=useState(null);const load=useCallback(()=>{if(!person)return;setLoading(true);fetchPersonnelAssets(person.id).then(setAssets).catch(e=>showToast(errorMessage(e),'error')).finally(()=>setLoading(false));},[person,showToast]);useEffect(load,[load]);if(!person)return null;return <><Modal open onClose={onClose} title={`${person.full_name}'s Items`} subtitle={`${person.employee_id} · ${person.department||'No department'}`} maxWidth="max-w-5xl">
  {loading?<p className="py-12 text-center text-slate-400">Loading assigned items...</p>:assets.length===0?<p className="rounded-xl bg-slate-50 py-12 text-center text-slate-500">No items are currently assigned.</p>:<div className="grid sm:grid-cols-2 gap-4">{assets.map(a=><button key={a.id} onClick={()=>setDetailId(a.id)} className="rounded-2xl border border-slate-200 p-5 text-left hover:border-blue-300 hover:shadow-md"><div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-blue-600">{a.asset_code}</p><h3 className="mt-1 font-bold text-slate-800">{a.inventory_name}</h3><p className="text-sm text-slate-500">{a.item_type}</p></div><Status value={a.status}/></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>Condition: <b className="capitalize text-slate-700">{a.current_condition}</b></span><span>Assigned: <b className="text-slate-700">{date(a.assigned_at)}</b></span><span className="col-span-2">Last maintenance: <b className="text-slate-700">{date(a.last_maintenance_date)}</b></span></div></button>)}</div>}
  </Modal>{detailId&&<AssetDetail assetId={detailId} people={people} onClose={()=>setDetailId(null)} onChanged={()=>{load();onChanged();}} showToast={showToast}/>}</>}

function AssetDetail({assetId,people,onClose,onChanged,showToast}){const [asset,setAsset]=useState(null),[action,setAction]=useState(null),[editMaintenance,setEditMaintenance]=useState(null),[showMaintenance,setShowMaintenance]=useState(false);const load=useCallback(()=>fetchAssetDetails(assetId).then(setAsset).catch(e=>showToast(errorMessage(e),'error')),[assetId,showToast]);useEffect(()=>{load();},[load]);if(!asset)return <Modal open onClose={onClose} title="Asset record"><p>Loading...</p></Modal>;const publicAppUrl=(import.meta.env.VITE_PUBLIC_APP_URL||window.location.origin).replace(/\/$/,'');const qrUrl=`${publicAppUrl}/asset/${asset.qr_token}`;
  function done(message){setAction(null);setEditMaintenance(null);load();onChanged();showToast(message);}
  async function removeRecord(record){if(!confirm(`Remove the maintenance record "${record.work_performed}"? An audit copy will be preserved.`))return;try{const r=await removeMaintenance(asset.id,record.id);done(r.message);}catch(e){showToast(errorMessage(e),'error');}}
  return <><Modal open onClose={onClose} title={asset.inventory_name} subtitle={`${asset.asset_code} · ${asset.item_type}`} maxWidth="max-w-5xl"><div className="grid items-start lg:grid-cols-[1fr_220px] gap-7 mb-7">
    <div><div className="grid sm:grid-cols-3 gap-3 mb-4"><Mini label="Status" value={asset.status?.replaceAll('_',' ')}/><Mini label="Condition" value={asset.current_condition}/><Mini label="Assigned to" value={asset.personnel_name||'Unassigned'}/><Mini label="Original price" value={money(asset.unit_price)}/><Mini label="Procured" value={date(asset.date_procured)}/><Mini label="Supplier" value={asset.procured_at||asset.supplier||'—'}/></div>
      <CostSummary asset={asset}/>
      <div className="flex flex-wrap gap-2"><Btn blue onClick={()=>setAction('maintenance')}>+ Maintenance</Btn>{asset.assignment_id&&<Btn onClick={()=>setAction('transfer')}>Transfer</Btn>}{asset.assignment_id&&<Btn onClick={()=>setAction('return')}>Return</Btn>}{asset.status!=='phased_out'&&<Btn danger onClick={()=>setAction('phase')}>Phase Out</Btn>}</div>
    </div><QrPanel url={qrUrl} code={asset.asset_code}/></div>
    <MaintenanceHistory records={asset.maintenance} open={showMaintenance} onToggle={()=>setShowMaintenance(value=>!value)} onEdit={record=>setEditMaintenance(record)} onRemove={removeRecord}/>
    <History title="Assignment history" empty="No assignment records." rows={asset.assignment_history.map(a=>({title:a.full_name,meta:`${date(a.assigned_at)} → ${a.returned_at?date(a.returned_at):'Current'} · ${a.status}`,body:a.notes}))}/>
    </Modal>
    {action&&<ActionModal type={action} asset={asset} people={people} onClose={()=>setAction(null)} onDone={done}/>} {editMaintenance&&<ActionModal type="maintenance" asset={asset} people={people} maintenanceRecord={editMaintenance} onClose={()=>setEditMaintenance(null)} onDone={done}/>}</>}

function QrPanel({url,code}){const ref=useRef();function download(){const canvas=ref.current?.querySelector('canvas');if(!canvas)return;const a=document.createElement('a');a.download=`${code}-QR.png`;a.href=canvas.toDataURL('image/png');a.click();}return <aside className="rounded-2xl bg-slate-50 p-5 text-center h-fit"><p className="text-sm font-bold text-slate-800">Asset QR Code</p><div ref={ref} className="my-4 inline-block rounded-xl bg-white p-3"><QRCodeCanvas value={url} size={160} level="H" includeMargin/></div><p className="break-all text-[10px] text-slate-400">{url}</p><button onClick={download} className="mt-4 w-full rounded-lg bg-slate-800 py-2 text-xs font-semibold text-white">Download QR</button></aside>}

function CostSummary({asset}){const summary=asset.maintenance_summary||{};return <section className="mb-6 overflow-hidden rounded-2xl border border-emerald-200 bg-emerald-50/60">
  <div className="grid grid-cols-1 sm:grid-cols-[1fr_auto_1fr_auto_1.2fr] items-center gap-3 p-4 text-center">
    <Cost label="Original price" value={asset.unit_price}/><span className="hidden sm:block text-xl text-emerald-400">+</span><Cost label={`Maintenance (${summary.record_count||0})`} value={summary.total_cost}/><span className="hidden sm:block text-xl text-emerald-400">=</span><Cost label="Total recorded cost" value={asset.total_recorded_cost} strong/>
  </div>
  <div className="border-t border-emerald-200 px-4 py-2 text-center text-xs text-emerald-700">Maintenance total: {money(summary.parts_cost)} parts + {money(summary.service_cost)} service</div>
  </section>}
function Cost({label,value,strong}){return <div><p className="text-[10px] font-semibold uppercase tracking-wide text-emerald-700">{label}</p><p className={`${strong?'text-2xl':'text-lg'} mt-1 font-bold text-emerald-900`}>{money(value)}</p></div>}

function MaintenanceHistory({records,open,onToggle,onEdit,onRemove}){return <section className="mb-7 overflow-hidden rounded-2xl border border-slate-200 bg-white"><button type="button" onClick={onToggle} aria-expanded={open} className="flex w-full items-center justify-between gap-4 bg-slate-50 px-5 py-4 text-left hover:bg-slate-100"><div><h3 className="font-bold text-slate-800">Complete Maintenance History</h3><p className="mt-1 text-xs text-slate-500">{open?'Click to close the drawer':'Click to view every maintenance record'}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-600 shadow-sm">{records.length} record{records.length===1?'':'s'}</span><span className={`flex h-8 w-8 items-center justify-center rounded-full bg-white text-slate-500 shadow-sm transition-transform duration-200 ${open?'rotate-180':''}`} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4"><path d="m6 9 6 6 6-6"/></svg></span></div></button>
  {open&&<div className="border-t border-slate-200 p-4 sm:p-5">{records.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-400">No maintenance records.</p>:<div className="space-y-4">{records.map(record=>{const total=Number(record.parts_cost||0)+Number(record.service_cost||0);return <article key={record.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
    <div className="flex flex-col gap-2 bg-slate-50 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-slate-800">{record.work_performed}</p><p className="mt-1 text-xs text-slate-500">Reported {date(record.date_reported)}{record.completion_date?` · Completed ${date(record.completion_date)}`:''}</p></div><div className="flex flex-wrap items-center gap-2"><Status value={record.maintenance_status}/><span className="rounded-lg bg-emerald-100 px-3 py-1.5 text-sm font-bold text-emerald-800">{money(total)}</span><button type="button" onClick={()=>onEdit(record)} className="rounded-lg bg-amber-100 px-3 py-1.5 text-xs font-semibold text-amber-800 hover:bg-amber-200">Edit</button><button type="button" onClick={()=>onRemove(record)} className="rounded-lg bg-red-100 px-3 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-200">Remove</button></div></div>
    <div className="grid gap-4 p-5 sm:grid-cols-2"><RecordInfo label="Reason / Problem" value={record.reason}/><RecordInfo label="Diagnosis" value={record.diagnosis}/><RecordInfo label="Work performed" value={record.work_performed}/><RecordInfo label="Parts or materials added" value={record.parts_added}/><RecordInfo label="Technician / Service provider" value={record.service_provider}/><RecordInfo label="Condition after maintenance" value={record.condition_after}/></div>
    <div className="grid grid-cols-3 border-t border-slate-100 bg-slate-50/60 text-center"><CostCell label="Parts" value={record.parts_cost}/><CostCell label="Service" value={record.service_cost}/><CostCell label="Record total" value={total} strong/></div>
    {record.notes&&<div className="border-t border-slate-100 px-5 py-3 text-xs text-slate-600"><b>Notes:</b> {record.notes}</div>}
  </article>})}</div>}</div>}
  </section>}
function RecordInfo({label,value}){return <div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700 capitalize">{value||'—'}</p></div>}
function CostCell({label,value,strong}){return <div className="border-r border-slate-100 px-3 py-3 last:border-r-0"><p className="text-[10px] uppercase text-slate-400">{label}</p><p className={`mt-1 ${strong?'font-bold text-emerald-700':'font-semibold text-slate-700'}`}>{money(value)}</p></div>}

function ActionModal({type,asset,people,onClose,onDone,maintenanceRecord=null}){const maintenanceInitial=maintenanceRecord?{...maintenanceRecord,date_reported:maintenanceRecord.date_reported?.slice(0,10)||today,completion_date:maintenanceRecord.completion_date?.slice(0,10)||'',parts_cost:String(maintenanceRecord.parts_cost||0),service_cost:String(maintenanceRecord.service_cost||0)}:{date_reported:today,reason:'',diagnosis:'',work_performed:'',parts_added:'',service_provider:'',parts_cost:'0',service_cost:'0',condition_after:asset.current_condition,maintenance_status:'completed',completion_date:today,notes:''};const configs={maintenance:{title:maintenanceRecord?'Edit Maintenance':'Add Maintenance',initial:maintenanceInitial},return:{title:'Return Item',initial:{returned_at:today,condition_on_return:asset.current_condition,notes:''}},transfer:{title:'Transfer Item',initial:{personnel_id:'',transfer_date:today,condition:asset.current_condition,notes:''}},phase:{title:'Phase Out Item',initial:{phase_out_date:today,reason:'',final_condition:asset.current_condition,disposal_method:'',approved_by:'',notes:''}}};const cfg=configs[type],[form,setForm]=useState(cfg.initial),[saving,setSaving]=useState(false),[error,setError]=useState('');const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));async function submit(e){e.preventDefault();setSaving(true);setError('');try{let r;if(type==='maintenance')r=maintenanceRecord?await updateMaintenance(asset.id,maintenanceRecord.id,form):await addMaintenance(asset.id,form);if(type==='return')r=await returnAsset(asset.id,form);if(type==='transfer')r=await transferAsset(asset.id,form);if(type==='phase')r=await phaseOutAsset(asset.id,form);onDone(r.message);}catch(err){setError(errorMessage(err));}finally{setSaving(false);}}
  return <Modal open onClose={onClose} title={cfg.title} subtitle={`${asset.asset_code} · ${asset.inventory_name}`}><form onSubmit={submit} className="grid sm:grid-cols-2 gap-4">{type==='maintenance'&&<><Field label="Date reported" type="date" name="date_reported" value={form.date_reported} onChange={change}/><Select label="Status" name="maintenance_status" value={form.maintenance_status} onChange={change} options={['reported','scheduled','in_progress','completed','cancelled']}/><Area label="Why maintenance was needed *" name="reason" value={form.reason} onChange={change} required/><Area label="Work performed *" name="work_performed" value={form.work_performed} onChange={change} required/><Area label="Diagnosis" name="diagnosis" value={form.diagnosis} onChange={change}/><Area label="Parts / materials added" name="parts_added" value={form.parts_added} onChange={change}/><Field label="Technician / provider" name="service_provider" value={form.service_provider} onChange={change}/><Field label="Completion date" type="date" name="completion_date" value={form.completion_date} onChange={change}/><Field label="Parts cost" type="number" step="0.01" name="parts_cost" value={form.parts_cost} onChange={change}/><Field label="Service cost" type="number" step="0.01" name="service_cost" value={form.service_cost} onChange={change}/><Select label="Condition after" name="condition_after" value={form.condition_after} onChange={change} options={['new','good','fair','poor','damaged']}/></>}
  {type==='return'&&<><Field label="Return date" type="date" name="returned_at" value={form.returned_at} onChange={change}/><Select label="Condition on return" name="condition_on_return" value={form.condition_on_return} onChange={change} options={['new','good','fair','poor','damaged']}/></>}
  {type==='transfer'&&<><label className="text-sm font-medium text-slate-700">Transfer to *<select required name="personnel_id" value={form.personnel_id} onChange={change} className={inputClass}><option value="">Select personnel</option>{people.filter(p=>p.id!==asset.personnel_id).map(p=><option value={p.id} key={p.id}>{p.full_name} — {p.department||'No department'}</option>)}</select></label><Field label="Transfer date" type="date" name="transfer_date" value={form.transfer_date} onChange={change}/><Select label="Current condition" name="condition" value={form.condition} onChange={change} options={['new','good','fair','poor','damaged']}/></>}
  {type==='phase'&&<><Field label="Phase-out date" type="date" name="phase_out_date" value={form.phase_out_date} onChange={change}/><Select label="Final condition" name="final_condition" value={form.final_condition} onChange={change} options={['good','fair','poor','damaged']}/><Area label="Reason *" name="reason" value={form.reason} onChange={change} required/><Field label="Disposal method" name="disposal_method" value={form.disposal_method} onChange={change}/><Field label="Approved by" name="approved_by" value={form.approved_by} onChange={change}/></>}
  <Area label="Notes" name="notes" value={form.notes} onChange={change} className="sm:col-span-2"/>{error&&<Error text={error}/>}<Submit saving={saving} text={cfg.title}/></form></Modal>}

const inputClass='mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-400';
function Field({label,...props}){return <label className="text-sm font-medium text-slate-700">{label}<input {...props} className={inputClass}/></label>}
function Select({label,options,...props}){return <label className="text-sm font-medium text-slate-700">{label}<select {...props} className={`${inputClass} capitalize`}>{options.map(o=><option key={o} value={o}>{o.replaceAll('_',' ')}</option>)}</select></label>}
function Area({label,className='',...props}){return <label className={`text-sm font-medium text-slate-700 ${className}`}>{label}<textarea {...props} rows="3" className={inputClass}/></label>}
function Submit({saving,text}){return <div className="sm:col-span-2 flex justify-end"><button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?'Saving...':text}</button></div>}
function Error({text}){return <p className="sm:col-span-2 rounded-lg bg-red-50 p-3 text-sm text-red-700">{text}</p>}
function Status({value}){return <span className="h-fit rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold uppercase text-blue-700">{value?.replaceAll('_',' ')}</span>}
function Mini({label,value}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-bold capitalize text-slate-700">{value}</p></div>}
function History({title,empty,rows}){return <section className="mb-6"><h3 className="mb-3 font-bold text-slate-800">{title}</h3>{rows.length===0?<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-400">{empty}</p>:<div className="space-y-2">{rows.map((r,i)=><div key={i} className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between gap-3"><p className="text-sm font-semibold text-slate-800">{r.title}</p><p className="text-right text-xs capitalize text-slate-400">{r.meta}</p></div>{r.body&&<p className="mt-2 text-xs text-slate-500">{r.body}</p>}</div>)}</div>}</section>}
